# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy backend - chat-wm-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn package -f backend/chat-backend/pom.xml
      
    - name: Move jar and web.config to staging directory
      run: mkdir staging && cp target/*.jar staging && cp web.config staging
      
    - name: Show staging files
      run: "ls staging"
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chat-wm-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a324962653ce4395ad072f783f5fd616 }}
        package: 'staging'
        
